loki:
  auth_enabled: false

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  storage:
    bucketNames:
      chunks: loki
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      bucketnames: loki
      endpoint: minio-minio-instance-hl.minio.svc.cluster.local:9000
      access_key_id: ${S3_ACCESS_KEY}
      secret_access_key: ${S3_SECRET_KEY}
      s3forcepathstyle: true
      insecure: true

  limits_config:
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32
    reject_old_samples: true
    reject_old_samples_max_age: 168h

  compactor:
    working_directory: /var/loki/compactor
    shared_store: s3

  commonConfig:
    replication_factor: 1

  extraArgs:
    - "-config.expand-env=true"

  extraEnv:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: access_key_id
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: secret_access_key


write:
  extraArgs:
    - "-config.expand-env=true"
  extraEnv:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: access_key_id
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: secret_access_key

read:
  extraArgs:
    - "-config.expand-env=true"
  extraEnv:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: access_key_id
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: secret_access_key

backend:
  extraArgs:
    - "-config.expand-env=true"
  extraEnv:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: access_key_id
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio-creds
          key: secret_access_key

test:
  enabled: false

monitoring:
  dashboards:
    enabled: true
    namespace: prometheus
  lokiCanary:
    enabled: false




# loki:
#   auth_enabled: false

#   schemaConfig:
#     configs:
#     - from: "2020-12-11"
#       store: boltdb-shipper
#       object_store: s3
#       schema: v12
#       index:
#         prefix: index_
#         period: 24h
#   limits_config:
#     allow_structured_metadata: false
#     ingestion_rate_mb: 16
#     ingestion_burst_size_mb: 32
#     reject_old_samples: true
#     reject_old_samples_max_age: 168h
#   storage:
#     bucketNames:
#       chunks: loki
#       ruler: loki-ruler     # optional, only if ruler is enabled
#       admin: loki-admin
#     type: s3
#     s3:
#       bucketnames: loki
#       endpoint: minio-minio-instance-hl.minio.svc.cluster.local:9000
#       access_key_id: ${S3_ACCESS_KEY}
#       secret_access_key: ${S3_SECRET_KEY}
#       s3forcepathstyle: true
#       insecure: true

#   extraArgs:
#     - "-config.expand-env=true"

#   extraEnv:
#     - name: S3_ACCESS_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: access_key_id
#     - name: S3_SECRET_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: secret_access_key

# write:
#   extraArgs:
#     - "-config.expand-env=true"
#   extraEnv:
#     - name: S3_ACCESS_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: access_key_id
#     - name: S3_SECRET_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: secret_access_key

# read:
#   extraArgs:
#     - "-config.expand-env=true"
#   extraEnv:
#     - name: S3_ACCESS_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: access_key_id
#     - name: S3_SECRET_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: secret_access_key

# backend:
#   extraArgs:
#     - "-config.expand-env=true"
#   extraEnv:
#     - name: S3_ACCESS_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: access_key_id
#     - name: S3_SECRET_KEY
#       valueFrom:
#         secretKeyRef:
#           name: loki-minio-creds
#           key: secret_access_key

# test:
#   enabled: false

# monitoring:
#   dashboards:
#     enabled: true
#     namespace: prometheus
#   lokiCanary:
#     enabled: false
